#!/bin/sh
SUBLIST_DIR=/data/jux/mackey_group/Ursula/projects/in_progress/spatial_topography_parcellations_ABCD/data/subjLists/release2/site14site20
COHORT_FILE=${SUBLIST_DIR}/n597_site14site20_cohort.csv

# THIS WORKS to pull all those that have completed fmriprep, or
#all those in a given list
#for sub in `ls *.html`
echo id0,id1,img >> ${COHORT_FILE} #add header
for sub in `cat ${SUBLIST_DIR}/n597_site14site16_t1andbold_fmriprep.txt` #check that this list works!
do
    #sub=${sub%*.html}
    #sub=sub-${sub}
    echo $sub
    #find . -type f | grep "${sub}_*"
    #find . -iregex '.*preproc_bold.nii.gz$\|.*cgi$' -exec grep -il '${sub}_task' '{}' ';'
    #find . -type f | grep "sub-${sub}_task-rest_run-[0-9][0-9]_space-T1w_desc-preproc_bold.nii.gz\$"| while read fname; do
    find . -type f | grep "${sub}_task-rest_run-.._space-T1w_desc-preproc_bold.nii.gz\$" | while read fname; do
    tmp=$(echo "$fname" | awk -F '_' '{print $3}') #this parses on underscores and pulls 'run-01'
    echo $sub,$tmp,${fname:2} >> ${COHORT_FILE}
done;
done;



for sub in `find . -maxdepth 1 -mindepth 1 -type d -name "sub-*" | sed -e 's|.*/sub-||'`:
do
echo $sub
#find . -type f -iname "${sub}_task-rest_run-[09]_space-T1w_desc-preproc_bold.nii.gz" # >> image_list.txt
#find .-type f -print | grep 'LMN2011
find . -type f -print | grep "^${sub}_task-rest_run-.._space-T1w_desc-preproc_bold.nii.gz\$"
#if needed full path can do readlink -f file.nii.gz
done
done
