#!/bin/sh

#Loop script for FMRIPREP
#$ -j y
#unset PYTHONPATH;
URSULA_PROJ=/data/picsl/mackey_group/Ursula/projects/in_progress
ERROR_DIR=/data/picsl/mackey_group/Ursula/projects/in_progress/spatial_topography_parcellations_ABCD/output/job_output
SUBLIST_DIR=${URSULA_PROJ}/spatial_topography_parcellations_ABCD/data/subjLists
SUB_FILE=${SUBLIST_DIR}/n138_one_site_0.2mm.txt
SCRIPTS_DIR=${URSULA_PROJ}/spatial_topography_parcellations_ABCD/code/ppc/fmriprep


for sub in `find . -maxdepth 1 -mindepth 1 -type d -name "sub-*" | sed -e 's|.*/sub-||'| tail -n 69`:
do
echo $sub
sleep 1
qsub -q all.q,basic.q,himem.q -j y -o $ERROR_DIR -l h_vmem=25.1G,s_vmem=25.0G ${SCRIPTS_DIR}/fmriprep_cmd2.sh ${sub}

done

##cleanup for those that weren't run in this first round
BIDS_folder=/data/jux/mackey_group/public_data/ABCD/bids_fast_track_site14/
output_dir=${BIDS_folder}/derivatives/fmriprep

for sub in `find . -maxdepth 1 -mindepth 1 -type d -name "sub-*" | sed -e 's|.*/sub-||'`:
do
if [ -d ${output_dir}/sub-$sub ]; then
  echo $sub
  echo 'it exists'
else
  echo $sub
  echo 'it doesnt exist'
  # sleep 1
  # qsub -q all.q,basic.q,himem.q -j y -o $ERROR_DIR -l h_vmem=25.1G,s_vmem=25.0G ${SCRIPTS_DIR}/fmriprep_cmd2.sh ${sub}
fi
done
